vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /img/avatar
            upload_destination: '%kernel.project_dir%/public/img/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer